### ISSUE TITLE
pokemon_list.txt should be one pokemon per line

### ISSUE THREAD

**Issue by justincely** [ZachSellman/pokereddit_bot#4]
the current content has all 150+ pokemon on a single line.  While this works fine in your program to read in, there are various technical, practical, and historical reasons why it's much better to go line-by-line for this.

One reason is to just keep it easy for review on tools like git/github.  They operate by showing the differences line-by-line; so if you have a misspelled pokemon at ANY point in the current single-line-list, then the entire line looks like it changed.  If you split it up, then only the specific line that changed will show up - which makes it easier to review and keep in your head.

This is also just the main pattern for computers reading things: line-by-line, not column-by-cloumn.  Think of a CSV or an xcel sheet.  If you wanted to enhance this pokemon list with additional attributes; like HP or attacks, or whatever - it's going to be very hard in this format, but very easy in line-by-line.

**Comment by ZachSellman** [comment]
That makes sense. I've been thinking of expanding the list to include each generation of pokemon, which would work much better this way as well.

**Comment by ZachSellman** [comment]
Tried closing this with the PR, but I probably formatted it incorrectly.
