### ISSUE TITLE
setup github actions to automatically run a linter

### ISSUE THREAD

**Issue by justincely** [ZachSellman/pokereddit_bot#5]
flake8 and maybe black would be good ones to start with.  There are a few things I see going through the code that I could individually recommend, but these will catch them for you and we can write issues to address the things they find. 

Github actions will take a little bit to learn, but it's valuable for sure.

**Comment by ZachSellman** [comment]
I have Black integrated with VSCode so it runs each save. Looking at actions is indeed a bit confusing; is this meant to be run on pull requests? Or integrated into GitHub itself for editing code in-browser instead of locally?

**Comment by justincely** [comment]
yeah, github actions is a form of Continuous Integration (CI).  Depending on how you configure it, it will run on every PR and/or every push of code.  You will put things there like formatters, unit tests, etc.  Then each time a PR is opened, the checks will run and ideally you'll go into settings and not allow code to go in unless it's passed the tests.

If you give me admin permissions here I can make the changes in the settings tab - otherwise I can show you what to do.  This pattern of ALWAYS doing a PR and never pushing to `main` is a good thing to get in the habit of.
